---
title: "`r emo::ji('package')` Developing Packages `r emo::ji('package')`"
subtitle: "The Life-Cycle of Creating and Deploying Packages with R"
author: "<br>Kyle Harris <br><i class='fab fa-twitter'></i> <i class='fab fa-instagram'></i> <i class='fab fa-github'></i> @KoderKow"
date: "<i class='fas fa-globe'></i> https://koderkow.rbind.io<br>Follow Along: **Coming Soon**"
output:
  xaringan::moon_reader:
    fig_catption: yes
    lib_dir: libs
    css: ["default", "metropolis", "metropolis-fonts", "custom.css"]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      highlightSpans: true
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

```{r, echo=FALSE}
library(emo) # for the sick emojis
```


# Overview

- [Presentation Goal](#presentation_goal)
- [Prerequisites](#prerequisites)
- [What is a Package?](#what_is_a_package)

---

name: presentation_goal

# Presentation Goal

I made this presentation to help bring together multiple sources of amazing information and tutorials to show how easy it is to not only create a package, but to integrate automated building, testing, and webpages by utilizing pre-built R packages. My goal is to help inspire others to create and contribute to packages that are used daily in R.

## Goals

- General understanding of packages
- Follow methods from Hadley's [*R Packages*][r-pkg-book] book for setting up your envinroment and package creating methods
- Hosting on github
- Automate build testing
- Code coverage
- TGenerate a package webpage with `pkgdown`
  - Automate `pkgdown` site with **Travis CI**

---

name: prerequisites

# Prerequisites

- Have these packages installed:
``` r
install.packages(c("devtools", "roxygen2", "testthat", "knitr"))
# get the development versions from github
devtools::install_github("r-lib/devtools")
devtools::install_github("r-lib/usethis")
```
- C compiler
  - Check if you have by running this in your console:
``` r
devtools::has_devel()
```
  - If `FALSE` is returned, follow section 1.3 in Hadley's book [*R Packages*][hadley-getting-started] for assistance in getting everything set up
  
- To host the package you will need Git and GitHub setup with RStudio
  - Follow Chapter 14.2 of [*R Packages*: Initial set up][git-setup] if you do not have this already

---

name: what_is_a_package

# What is a Package?

<!-- links used in slides -->
[r-pkg-book]: https://r-pkgs.org/
[git-setup]: https://r-pkgs.org/git.html#git-rstudio
[hadley-getting-started]: https://r-pkgs.org/intro-why.html#intro-get